/* -*- Mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; tab-width: 40 -*- */
/* vim: set ts=2 et sw=2 tw=40: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

dictionary NetworkPoliciesPolicyConnection
{
  DOMString connectionType;
  boolean allowed;
  boolean prefered;
  long max;
};

dictionary NetworkPoliciesPolicy
{
  DOMString app;
  boolean allowNetworkAccess;
  jsval policies;                                  // NetworkPoliciesPolicyConnection[]
};

[scriptable, uuid(d7dcbc77-edf4-40c8-9497-4dca4cf750c7)]
interface nsIDOMMozNetworkPoliciesManager : nsISupports
{
  readonly attribute jsval installedApplications;  // DOMString[]
  readonly attribute jsval connectionTypes;        // DOMString[]

  /**
   * Assing new policy
   *
   * typeof policies = NetworkPoliciesPolicy
   *
   * If policy.app is not provided, assing default policy
   */
  boolean set(in jsval policy);

  /**
   * Recover a policy
   */
  jsval get(in DOMString application);
};
